In [1]:
from sklearn.datasets import fetch_mldata
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import model_selection 

In [2]:
mnist=fetch_mldata('mnist original')

C:\Users\Babi\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function fetch_mldata is deprecated; fetch_mldata was deprecated in version 0.20 and will be removed in version 0.22
  warnings.warn(msg, category=DeprecationWarning)
C:\Users\Babi\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function mldata_filename is deprecated; mldata_filename was deprecated in version 0.20 and will be removed in version 0.22
  warnings.warn(msg, category=DeprecationWarning)


In [3]:
x=mnist['data']
y=mnist['target']

In [33]:
y

array([0., 0., 0., ..., 9., 9., 9.])

In [34]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [4]:
y=y.astype("int32")
x=x/255.0

In [36]:
y

array([0, 0, 0, ..., 9, 9, 9])

In [37]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [10]:
X_train,X_test,y_train,y_test=model_selection.train_test_split(x,y,test_size=0.20)

In [13]:
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [26]:
y_predict=clf.score(X_test,y_test)
print(y_predict*100,"%")

96.67142857142858 %


In [23]:
from sklearn.metrics import classification_report

In [27]:
predictions=clf.predict(X_test)

In [30]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98      1372
           1       0.98      0.99      0.99      1574
           2       0.95      0.96      0.96      1367
           3       0.96      0.94      0.95      1411
           4       0.97      0.98      0.97      1376
           5       0.97      0.95      0.96      1246
           6       0.97      0.98      0.98      1378
           7       0.97      0.97      0.97      1503
           8       0.95      0.95      0.95      1336
           9       0.96      0.96      0.96      1437

   micro avg       0.97      0.97      0.97     14000
   macro avg       0.97      0.97      0.97     14000
weighted avg       0.97      0.97      0.97     14000

